feat: ajusta endpoint editar
fga-eps-mds/2022-1-schedula-gestor-de-usuarios pull request #21
Opened 2022-08-18 13:57 UTC by brun0sk

Ajustei o endpoint editar e o test put.

2022-08-18 20:21 UTC, Sayuck requested changes
Modificar pontos observados.

2022-08-18 20:21 UTC, Sayuck commented on src/routers/Template_put.py
> +    acess: str | None = None
Coloque este arquivo dentro de uma pasta com nome schemas dentro da models para deixar mais organizado

2022-08-18 20:21 UTC, Sayuck commented on tests/test_put_user.py
> +    assert data["job_role"] == "string"
Adicione outros testes de put para validar as modificações.

2022-08-19 02:16 UTC, brun0sk commented on tests/test_put_user.py
> +    assert data["job_role"] == "string"
Fiz as modificações solicitadas.

2022-08-20 20:05 UTC, Sayuck approved these changes

2022-08-20 20:10 UTC, merged